version: '3.3'
services:
  lb:
    image: ritukamboj27/lb:latest
    build:
      context: .     
    ports:
      - 80:80
    environment:
      - PROXY_UPSTREAM
    depends_on:
      - webapp
  webapp:
    image: jfahrer/demo_web_app:wait_for_pg
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
    depends_on:
      - pg        

  pg:
    image: postgres:9.6.6-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD  
    volumes:
      - pg-data:/var/lib/postgresql/data


volumes:  
  pg-data:

